### ISSUE TITLE
Update icons with in-game equivalents 

### ISSUE THREAD

**Issue by phillipse01** [andrerfcsantos/valorant-agent-picker#3]
The Icons are currently screen caps of the half-body image. Update the images to align with in-game icons.

**Comment by andrerfcsantos** [comment]
This will be done as soon as we have a reliable source for these images, such as the wiki.

**Comment by zw5** [comment]
They are on the wiki now:
Brimstone: https://static.wikia.nocookie.net/valorant/images/4/4d/Brimstone_icon.png
Viper: https://static.wikia.nocookie.net/valorant/images/5/5f/Viper_icon.png
Omen: https://static.wikia.nocookie.net/valorant/images/b/b0/Omen_icon.png
Cypher: https://static.wikia.nocookie.net/valorant/images/8/88/Cypher_icon.png
Sage: https://static.wikia.nocookie.net/valorant/images/7/74/Sage_icon.png
Breach: https://static.wikia.nocookie.net/valorant/images/5/53/Breach_icon.png
Sova: https://static.wikia.nocookie.net/valorant/images/4/49/Sova_icon.png
Jett: https://static.wikia.nocookie.net/valorant/images/3/35/Jett_icon.png
Phoenix: https://static.wikia.nocookie.net/valorant/images/1/14/Phoenix_icon.png
Raze: https://static.wikia.nocookie.net/valorant/images/9/9c/Raze_icon.png

**Comment by andrerfcsantos** [comment]
> They are on the wiki now:
> Brimstone: https://static.wikia.nocookie.net/valorant/images/4/4d/Brimstone_icon.png
> Viper: https://static.wikia.nocookie.net/valorant/images/5/5f/Viper_icon.png
> Omen: https://static.wikia.nocookie.net/valorant/images/b/b0/Omen_icon.png
> Cypher: https://static.wikia.nocookie.net/valorant/images/8/88/Cypher_icon.png
> Sage: https://static.wikia.nocookie.net/valorant/images/7/74/Sage_icon.png
> Breach: https://static.wikia.nocookie.net/valorant/images/5/53/Breach_icon.png
> Sova: https://static.wikia.nocookie.net/valorant/images/4/49/Sova_icon.png
> Jett: https://static.wikia.nocookie.net/valorant/images/3/35/Jett_icon.png
> Phoenix: https://static.wikia.nocookie.net/valorant/images/1/14/Phoenix_icon.png
> Raze: https://static.wikia.nocookie.net/valorant/images/9/9c/Raze_icon.png

Thanks for the heads up.

I have an update planned for the site, and I'll be sure to include this.

**Comment by andrerfcsantos** [comment]
The new icons are now live!
